title: Business AI and Analytics Centre
subtitle: Durham University Business School
description: Exploring how artificial intelligence and analytics are transforming organisations, markets, professions and the future of business at Durham University Business School.
url: https://business-ai-analytics-centre.github.io
baseurl: ""
locale: en-GB
timezone: Europe/London

include:
  - _pages

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from

markdown: kramdown
permalink: /:categories/:title/

defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: page

repository: Business-AI-Analytics-Centre/business-ai-analytics-centre.github.io
github: [metadata]
centre_email: ""
